name: CI Pipeline for Crate DB

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.1.11
          poetry install

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 crate_db tests

      - name: Run tests
        run: |
          poetry run pytest
