# FOCA configuration
# Available in app context as attributes of `current_app.config.foca`
# Automatically validated via FOCA
# Cf. https://foca.readthedocs.io/en/latest/modules/foca.models.html

# Server configuration
# Cf. https://foca.readthedocs.io/en/latest/modules/foca.models.html#foca.models.config.ServerConfig
server:
  host: "0.0.0.0"
  port: 8080
  debug: True
  environment: development
  testing: False
  use_reloader: True

# Security configuration
# Cf. https://foca.readthedocs.io/en/latest/modules/foca.models.html#foca.models.config.SecurityConfig
security:
  auth:
    required: True
    add_key_to_claims: True
    algorithms:
      - RS256
    allow_expired: False
    audience: null
    validation_methods:
      - userinfo
      - public_key
    validation_checks: all


# Database configuration
# Cf. https://foca.readthedocs.io/en/latest/modules/foca.models.html#foca.models.config.DBConfig
db:
  host: mongodb
  port: 27017
  dbs:
    ro-crate-db:
      collections:
        ro-crates:
          indexes: null

# API configuration
# Cf. https://foca.readthedocs.io/en/latest/modules/foca.models.html#foca.models.config.APIConfig
api:
  specs:
    - path:
        - api/crate-db-specs.yaml
      add_operation_fields:
        x-openapi-router-controller: ga4gh.controllers.server
        security:
          - bearerAuth: []
      add_security_fields:
        x-bearerInfoFunc: app.validate_token
      disable_auth: True
      connexion:
        strict_validation: True
        validate_responses: False
        options:
          swagger_ui: True
          serve_spec: True

# Exception configuration
# Cf. https://foca.readthedocs.io/en/latest/modules/foca.models.html#foca.models.config.ExceptionConfig
Exceptions:
  required_members: [['message'], ['code']]
  status_member: ['code']
  exceptions: exceptions.exceptions