components:
  parameters:
    rocrate_id:
      description: ID of the ROCrate
      in: path
      name: rocrate_id
      required: true
      schema:
        example: 609d4b156f6d1972e7f78c87
        type: string
  schemas:
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
    ROCrateBase:
      description: The base schema for an ROCrate.
      properties:
        description:
          description: A description of the ROCrate.
          example: This is an example description of an ROCrate.
          type: string
        title:
          description: The title of the ROCrate.
          example: Example ROCrate
          type: string
        zenodo_info:
          description: Additional information for Zenodo.
          example:
            doi: 10.1234/example.doi
            metadata:
              '...': null
          type: object
      required:
      - title
      - description
      type: object
    ROCrateRequest:
      allOf:
      - $ref: '#/components/schemas/ROCrateBase'
      - properties:
          rocrate:
            description: The ROCrate file to upload.
            example: rocrate.zip
            format: binary
            type: string
        required:
        - rocrate
        type: object
    ROCrateResponse:
      allOf:
      - $ref: '#/components/schemas/ROCrateBase'
      - properties:
          _id:
            description: The unique identifier for the ROCrate.
            example: 60b6c0f9f1d2c12a5c7d6b8e
            type: string
          created_at:
            description: The creation date of the ROCrate.
            example: 2023-01-01 12:00:00+00:00
            format: date-time
            type: string
          rocrate:
            description: The link to the ROCrate file in MinIO.
            example: https://minio.example.com/rocrates/rocrate.zip
            type: string
          updated_at:
            description: The last update date of the ROCrate.
            example: 2023-01-02 12:00:00+00:00
            format: date-time
            type: string
          user_id:
            description: The user ID extracted from the access token.
            example: 1234567890abcdef
            type: string
        type: object
info:
  description: Microservice for managing ROCrates
  title: Crate DB Microservice
  version: 1.0.0
openapi: 3.0.0
paths:
  /rocrates:
    get:
      description: Returns a list of all ROCrates stored in the database.
      operationId: listROCrates
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ROCrateResponse'
                type: array
          description: OK
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request is unauthorized.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The requester is not authorized to perform this action.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Resource not found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get all ROCrates
      x-openapi-router-controller: ga4gh.controllers.server
    post:
      description: Stores a new crate in the database and uploads the zip file to
        MinIO.
      operationId: createROCrate
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ROCrateRequest'
              x-body-name: rocrate_data
        required: true
      responses:
        '201':
          $ref: '#/components/schemas/ROCrateResponse'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request is unauthorized.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The requester is not authorized to perform this action.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Creates a new ROCrate
      x-openapi-router-controller: ga4gh.controllers.server
  /rocrates/{rocrate_id}:
    delete:
      description: Delete an existing ROCrate
      operationId: deleteROCrate
      parameters:
      - $ref: '#/components/parameters/rocrate_id'
      responses:
        '204':
          description: No Content
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request is unauthorized.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The requester is not authorized to perform this action.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Resource not found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Delete a specific ROCrate by ID
      x-openapi-router-controller: ga4gh.controllers.server
    get:
      description: Returns a specific ROCrate stored in the database.
      operationId: getROCrate
      parameters:
      - $ref: '#/components/parameters/rocrate_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ROCrateResponse'
          description: OK
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request is unauthorized.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The requester is not authorized to perform this action.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Resource not found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get a specific ROCrate by ID
      x-openapi-router-controller: ga4gh.controllers.server
    put:
      description: Updates an existing crate in the database and uploads the zip file
        to MinIO.
      operationId: updateROCrate
      parameters:
      - $ref: '#/components/parameters/rocrate_id'
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ROCrateRequest'
              x-body-name: rocrate
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ROCrateResponse'
          description: Crate updated successfully
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The request is unauthorized.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The requester is not authorized to perform this action.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Resource not found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Update an existing RO-Crate
      x-openapi-router-controller: ga4gh.controllers.server
servers:
- url: http://localhost/
